/*
 * Roboto Condensed Bold, generated by tools/gen_fonts.sh.
 *
 * Two ladders, one per panel. The C6 sizes are not the S3 list doubled: that
 * panel has 2x the pixels but only 1.4x the physical size, so each step is
 * scaled by the density ratio (~1.43) to hold the same millimetre height that
 * spec 2.2's legibility floor is written in. Derived in geometry.c.
 */
#pragma once

#include "lvgl.h"

/* S3 hero sizes (240x240, ~220 PPI) */
LV_FONT_DECLARE(stripe_sans_24)
LV_FONT_DECLARE(stripe_sans_32)
LV_FONT_DECLARE(stripe_sans_40)
LV_FONT_DECLARE(stripe_sans_52)
LV_FONT_DECLARE(stripe_sans_60)
LV_FONT_DECLARE(stripe_sans_64)
LV_FONT_DECLARE(stripe_sans_76)
LV_FONT_DECLARE(stripe_sans_88)
LV_FONT_DECLARE(stripe_sans_96)

/* S3 chrome */
LV_FONT_DECLARE(stripe_sans_18)
LV_FONT_DECLARE(stripe_sans_20)
LV_FONT_DECLARE(stripe_sans_22)

/* C6 hero sizes (480x480, ~314 PPI) */
LV_FONT_DECLARE(stripe_sans_35)
LV_FONT_DECLARE(stripe_sans_46)
LV_FONT_DECLARE(stripe_sans_58)
LV_FONT_DECLARE(stripe_sans_74)
LV_FONT_DECLARE(stripe_sans_86)
LV_FONT_DECLARE(stripe_sans_92)
LV_FONT_DECLARE(stripe_sans_104)
LV_FONT_DECLARE(stripe_sans_108)
LV_FONT_DECLARE(stripe_sans_120)
LV_FONT_DECLARE(stripe_sans_126)
LV_FONT_DECLARE(stripe_sans_137)

/* C6 chrome */
LV_FONT_DECLARE(stripe_sans_26)
LV_FONT_DECLARE(stripe_sans_29)
LV_FONT_DECLARE(stripe_sans_31)

/*
 * Font for a pixel size, or the nearest available. Sizes come from the
 * per-target ladder in hero_size.c and the layout constants in layout.h, so a
 * miss here means those disagree with what gen_fonts.sh produced.
 */
const lv_font_t *font_for_size(int size_px);
