/*
 * Roboto Condensed Bold, generated by tools/gen_fonts.sh.
 *
 * Sizes are derived in geometry.c from physical height rather than pixel
 * count: spec 2.2 states its legibility floor in millimetres at 50cm, so each
 * step holds a real-world size on this panel's ~314 PPI.
 */
#pragma once

#include "lvgl.h"



/* Hero sizes (480x480, ~314 PPI) */
LV_FONT_DECLARE(stripe_sans_35)
LV_FONT_DECLARE(stripe_sans_46)
LV_FONT_DECLARE(stripe_sans_58)
LV_FONT_DECLARE(stripe_sans_74)
LV_FONT_DECLARE(stripe_sans_86)
LV_FONT_DECLARE(stripe_sans_92)
LV_FONT_DECLARE(stripe_sans_104)
LV_FONT_DECLARE(stripe_sans_108)
LV_FONT_DECLARE(stripe_sans_120)
LV_FONT_DECLARE(stripe_sans_126)
LV_FONT_DECLARE(stripe_sans_137)

/* Chrome */
LV_FONT_DECLARE(stripe_sans_26)
LV_FONT_DECLARE(stripe_sans_29)
LV_FONT_DECLARE(stripe_sans_31)

/*
 * Font for a pixel size, or the nearest available. Sizes come from the
 * per-target ladder in hero_size.c and the layout constants in layout.h, so a
 * miss here means those disagree with what gen_fonts.sh produced.
 */
const lv_font_t *font_for_size(int size_px);
