/*
 * Hero value auto-sizing and text width measurement.
 *
 * Pure arithmetic, no ESP-IDF or LVGL dependencies, so it builds and tests on
 * the host. See hero_size.h for why this measures per glyph rather than using
 * the spec's 0.6em monospace constant.
 */
#include "hero_size.h"
#include "layout.h"

#include <stdint.h>

/*
 * Bitmap font sizes we ship for hero values, ascending.
 * Must stay in sync with tools/gen_fonts.sh and fonts/fonts.c.
 */
const int hero_font_sizes[] = {24, 32, 40, 52, 60, 64, 76, 88, 96};
const size_t hero_font_sizes_count =
    sizeof(hero_font_sizes) / sizeof(hero_font_sizes[0]);

/*
 * Advance width per glyph, in thousandths of an em, for SF Compact Bold.
 * Index 0 is ' ' (0x20); the table runs to 'z' (0x7A), matching the range
 * generated by tools/gen_fonts.sh.
 *
 * Extracted from the instantiated font file -- regenerate this table if the
 * face or weight changes, or the sizing will silently disagree with what LVGL
 * actually renders.
 */
#define GLYPH_FIRST 0x20
#define GLYPH_LAST  0x7A

static const uint16_t glyph_adv_x1000[] = {
     220, 308, 538, 637, 620, 798, 700, 280, 393, 392, 480, 619, 257, 410, 311, 392,
     640, 489, 599, 612, 634, 623, 639, 573, 649, 639, 318, 316, 620, 619, 620, 510,
     871, 658, 651, 659, 685, 585, 559, 672, 723, 316, 573, 662, 531, 835, 706, 695,
     624, 697, 655, 629, 561, 698, 652, 901, 622, 607, 608, 392, 392, 392, 485, 446,
     488, 571, 622, 556, 623, 573, 424, 614, 623, 311, 310, 591, 304, 908, 620, 588,
     621, 620, 433, 539, 424, 618, 555, 819, 573, 572, 522,
};

/* Widest glyph in the table. Unknown characters use this so that unmeasurable
 * text errs toward a smaller font rather than overflowing the column. */
#define GLYPH_FALLBACK_X1000 908

static uint16_t advance_x1000(unsigned char c)
{
    if (c < GLYPH_FIRST || c > GLYPH_LAST) {
        return GLYPH_FALLBACK_X1000;
    }
    return glyph_adv_x1000[c - GLYPH_FIRST];
}

int text_width_px(const char *text, int size_px)
{
    if (text == NULL || size_px <= 0) {
        return 0;
    }

    /* Accumulate in thousandths to avoid compounding rounding error across
     * glyphs, then round once at the end. */
    uint32_t total_x1000 = 0;
    for (const unsigned char *p = (const unsigned char *)text; *p; p++) {
        total_x1000 += advance_x1000(*p);
    }

    return (int)((total_x1000 * (uint32_t)size_px + 500) / 1000);
}

_Bool text_fits(const char *text, int size_px)
{
    return text_width_px(text, size_px) <= TEXT_COLUMN_PX;
}

int hero_size_for_text(const char *text)
{
    if (text == NULL || text[0] == '\0') {
        return 0;
    }

    /* Largest available size that fits, never above the cap. */
    int chosen = 0;
    for (size_t i = 0; i < hero_font_sizes_count; i++) {
        int candidate = hero_font_sizes[i];
        if (candidate <= SIZE_HERO_MAX && text_fits(text, candidate)) {
            chosen = candidate;
        }
    }

    if (chosen == 0) {
        /* Even the smallest size overflows; the caller should abbreviate. */
        chosen = hero_font_sizes[0];
    }

    return chosen;
}
