/*
 * Hero value auto-sizing and text width measurement.
 *
 * Pure arithmetic, no ESP-IDF or LVGL dependencies, so it builds and tests on
 * the host. See hero_size.h for why this measures per glyph rather than using
 * the spec's 0.6em monospace constant.
 */
/* Only present in the ESP-IDF build; the host harness compiles without it and
 * falls through to the S3 ladder, which is what the host tests expect. */
#ifdef ESP_PLATFORM
#include "sdkconfig.h"
#endif

#include "hero_size.h"
#include "layout.h"

#include <stdint.h>

/*
 * Bitmap font sizes we ship for hero values, ascending.
 * Must stay in sync with tools/gen_fonts.sh and fonts/fonts.c.
 */
/*
 * The hero ladder is per-panel. The C6 sizes are not the S3 list doubled: that
 * panel is 2x the pixels but only 1.4x the physical size, so each step is
 * scaled by the density ratio to hold the same millimetre height (geometry.c).
 */
/* BOARD_C6_AMOLED_216 is the Arduino port's selector -- it has no
 * sdkconfig.h, so CONFIG_IDF_TARGET_ESP32C6 never appears there and the C6
 * would quietly take the S3 ladder. Must match the condition in layout.h. */
#if defined(CONFIG_IDF_TARGET_ESP32C6) || defined(BOARD_C6_AMOLED_216)
const int hero_font_sizes[] = {35, 46, 58, 74, 86, 92, 108, 126, 137};
#else
const int hero_font_sizes[] = {24, 32, 40, 52, 60, 64, 76, 88, 96};
#endif
const size_t hero_font_sizes_count =
    sizeof(hero_font_sizes) / sizeof(hero_font_sizes[0]);

/*
 * The ladder above and the geometry in layout.h are selected by two separate
 * preprocessor conditions, and nothing but this check keeps them agreeing. If
 * they drift -- a new board flag added to one and not the other -- the result
 * is a deck laid out for one panel and typed for the other, which renders
 * without error and is wrong only by measurement. Fail the build instead.
 *
 * SIZE_HERO_MAX comes from layout.h; the top of the ladder must be the same
 * value the layout believes it is reserving space for.
 */
#if defined(CONFIG_IDF_TARGET_ESP32C6) || defined(BOARD_C6_AMOLED_216)
_Static_assert(SIZE_HERO_MAX == 137,
               "C6 ladder selected but layout.h did not pick the C6 geometry");
_Static_assert(SIZE_HERO_MIN == 35,
               "C6 ladder selected but layout.h did not pick the C6 geometry");
#else
_Static_assert(SIZE_HERO_MAX == 96,
               "S3 ladder selected but layout.h did not pick the S3 geometry");
_Static_assert(SIZE_HERO_MIN == 24,
               "S3 ladder selected but layout.h did not pick the S3 geometry");
#endif

/*
 * Advance width per glyph, in thousandths of an em, for Roboto Condensed Bold.
 * Index 0 is ' ' (0x20); the table runs to 'z' (0x7A), matching the range
 * generated by tools/gen_fonts.sh.
 *
 * Extracted from the vendored font file -- regenerate with
 * tools/dump_advances.py if the face or weight changes, or the sizing will
 * silently disagree with what LVGL actually renders.
 *
 * Note digits 0-9 are all 505: Roboto Condensed has tabular figures, so this
 * face happens to give us the anti-jitter property spec 5.4 wanted, even
 * though it is proportional for letters.
 */
#define GLYPH_FIRST 0x20
#define GLYPH_LAST  0x7A

static const uint16_t glyph_adv_x1000[] = {
     230, 261, 321, 528, 505, 638, 579, 162, 323, 324, 454, 476, 245, 361, 291, 332,
     505, 505, 505, 505, 505, 505, 505, 505, 505, 505, 273, 253, 447, 503, 454, 447,
     766, 597, 561, 570, 565, 491, 476, 585, 614, 270, 490, 553, 479, 758, 612, 604,
     568, 604, 553, 540, 542, 571, 578, 750, 560, 542, 530, 264, 381, 264, 391, 400,
     331, 471, 495, 460, 496, 479, 328, 503, 492, 252, 245, 478, 252, 742, 492, 498,
     495, 497, 331, 454, 307, 492, 449, 633, 452, 445, 452,
};

/* Widest glyph in the table. Unknown characters use this so that unmeasurable
 * text errs toward a smaller font rather than overflowing the column. */
#define GLYPH_FALLBACK_X1000 766

static uint16_t advance_x1000(unsigned char c)
{
    if (c < GLYPH_FIRST || c > GLYPH_LAST) {
        return GLYPH_FALLBACK_X1000;
    }
    return glyph_adv_x1000[c - GLYPH_FIRST];
}

int text_width_px(const char *text, int size_px)
{
    if (text == NULL || size_px <= 0) {
        return 0;
    }

    /* Accumulate in thousandths to avoid compounding rounding error across
     * glyphs, then round once at the end. */
    uint32_t total_x1000 = 0;
    for (const unsigned char *p = (const unsigned char *)text; *p; p++) {
        total_x1000 += advance_x1000(*p);
    }

    return (int)((total_x1000 * (uint32_t)size_px + 500) / 1000);
}

_Bool text_fits(const char *text, int size_px)
{
    return text_width_px(text, size_px) <= TEXT_COLUMN_PX;
}

int hero_size_for_text(const char *text)
{
    if (text == NULL || text[0] == '\0') {
        return 0;
    }

    /* Largest available size that fits, never above the cap. */
    int chosen = 0;
    for (size_t i = 0; i < hero_font_sizes_count; i++) {
        int candidate = hero_font_sizes[i];
        if (candidate <= SIZE_HERO_MAX && text_fits(text, candidate)) {
            chosen = candidate;
        }
    }

    if (chosen == 0) {
        /* Even the smallest size overflows; the caller should abbreviate. */
        chosen = hero_font_sizes[0];
    }

    return chosen;
}
